(define (eval-assignment exp env) 
  (set-variable-value! (assignment-variable exp)
		       (eval (assignment-value exp) env)
		       env)
  'ok)

(define (eval-definition exp env) 
  (set-variable! (definition-variable exp)
		 (eval (definition-value exp) env)
		 env)
  'ok)
